name=ESP32-Net
version=1.0.0
author=Neal Stephenson
maintainer=Neal Stephenson <nealstep@gmail.com>
sentence=A Simple ESP32 Networking Library
paragraph=just include an call init, handles reconnection and some basic UDP sending tasks
category=Network
url=https://github.com/nealstep/ESP32-Net
architectures=ESP32
